# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: b4b1da38d8a0745e3e6f38a1b410863ea12252b230f1bd010bcc286c7d71b425c582088c38ce9d57b51021e410d52f88377d61aa7de22311299bd330db7bd800

test:
  secret_key_base: 1eacdcb02abcbaaa54ecd956eb91316a135e02ecfca7d70da0ae50135876ff73177027809c83df705ed974ba5db845c4c7e6ba2eba308dbeeb9e20bf311f57ea

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
